Sprint 15
MaxCode2023/Tracker pull request #3
Opened 2023-04-29 09:20 UTC by MaxCode2023

2023-04-30 07:04 UTC, protos17 requested changes

2023-04-30 07:04 UTC, protos17 commented on Tracker/CoreData/TrackerCategoryStore.swift
> +        let _ = [
Если тестовые больше не нужны, рекомендую удалить

2023-04-30 07:04 UTC, protos17 commented on Tracker/CreateTracker/CreateTrackerViewController.swift
> +    let createEvent = UIButton()
Рекомендую UI элементы указать как private

2023-04-30 07:04 UTC, protos17 commented on Tracker/CreateTracker/NewTracker/Cells/ColorCell.swift
> +import Foundation
При импорте UIKit можно не импортировать Foundation, потому что первый содержит в себе второй

2023-04-30 07:04 UTC, protos17 commented on Tracker/CreateTracker/NewTracker/Cells/ColorCell.swift
> +    let mainView = UIView()
Рекомендую указать как private

2023-04-30 07:04 UTC, protos17 commented on Tracker/CreateTracker/NewTracker/Cells/ColorCell.swift
> +final public class ColorCell: UICollectionViewCell {
Рекомендую убрать все области видимости public в проекте, достаточно internal

2023-04-30 07:04 UTC, protos17 commented on Tracker/CreateTracker/NewTracker/Cells/EmojiCell.swift
> +import Foundation
Можно убрать

2023-04-30 07:04 UTC, protos17 commented on Tracker/CreateTracker/NewTracker/Schedule/ui/ScheduleCell.swift
> +    var delegate: ScheduleCellDelegate? = nil
Если переменная опциональна, то у нее уже присвоено значение по умолчанию - nil, можно дополнительно это не указывать

2023-04-30 07:04 UTC, protos17 commented on Tracker/TrackersViewController/SupplementaryView.swift
> +class SupplementaryView: UICollectionReusableView {
Рекомендую указать как final

2023-04-30 07:04 UTC, protos17 commented on Tracker/TrackersViewController/TrackerCell/TrackerCell.swift
> +import Foundation
Рекомендую удалить

2023-04-30 07:04 UTC, protos17 commented on Tracker/TrackersViewController/TrackerCell/TrackerCell.swift
> +    let backView = UIView()
Рекомендую переменным и константам присвоить область видимости private

2023-04-30 07:04 UTC, protos17 commented on Tracker/TrackersViewController/TrackersViewController.swift
> +       // setVisibleCategories()
Лишний закомментированный код рекомендую удалять

2023-05-02 14:04 UTC, MaxCode2023 commented on Tracker/CoreData/TrackerCategoryStore.swift
> +        let _ = [
нужны)

2023-05-02 14:04 UTC, MaxCode2023 commented on Tracker/CreateTracker/CreateTrackerViewController.swift
> +    let createEvent = UIButton()
плюс

2023-05-02 14:04 UTC, MaxCode2023 commented on Tracker/CreateTracker/NewTracker/Cells/ColorCell.swift
> +import Foundation
плюс

2023-05-02 14:05 UTC, MaxCode2023 commented on Tracker/CreateTracker/NewTracker/Cells/ColorCell.swift
> +    let mainView = UIView()
плюс

2023-05-02 14:05 UTC, MaxCode2023 commented on Tracker/CreateTracker/NewTracker/Cells/ColorCell.swift
> +final public class ColorCell: UICollectionViewCell {
plus

2023-05-02 14:06 UTC, MaxCode2023 commented on Tracker/CreateTracker/NewTracker/Schedule/ui/ScheduleCell.swift
> +    var delegate: ScheduleCellDelegate? = nil
Всё равно стараюсь указывать - для наглядности)

2023-05-02 14:06 UTC, MaxCode2023 commented on Tracker/TrackersViewController/SupplementaryView.swift
> +class SupplementaryView: UICollectionReusableView {
plus

2023-05-02 14:07 UTC, MaxCode2023 commented on Tracker/TrackersViewController/TrackerCell/TrackerCell.swift
> +import Foundation
plus

2023-05-02 14:08 UTC, MaxCode2023 commented on Tracker/TrackersViewController/TrackerCell/TrackerCell.swift
> +    let backView = UIView()
plus

2023-05-02 14:09 UTC, MaxCode2023 commented on Tracker/TrackersViewController/TrackersViewController.swift
> +       // setVisibleCategories()
plus

2023-05-02 16:48 UTC, protos17 requested changes

2023-05-02 16:48 UTC, protos17 commented on Tracker/CreateTracker/NewTracker/NewTrackerViewController.swift
> +        if choosedEmoji == nil || choosedColor == nil || choosedWeekday == nil || nameTrackerTextField.text?.isEmpty ?? true || nameTrackerTextField.text == " " {
Здесь кнопка создания блокируется и у нерегулярного события, рекомендую эту проверку делать одновременно с типом события и у нерегулярного события эту проверку убрать

2023-05-02 16:48 UTC, protos17 commented on Tracker/TrackersViewController/TrackersViewController.swift
> +    @objc func addButtonTapped() {
Рекомендую @objc методы тоже указывать как private

2023-05-02 16:48 UTC, protos17 commented on Tracker/TrackersViewController/TrackersViewController.swift
> +import Foundation
При импорте UIKit можно не импортировать Foundation, потому что первый содержит в себе второй

2023-05-02 16:48 UTC, protos17 commented on Tracker/TrackersViewController/TrackerCell/TrackerCell.swift
> +            plusButtonImage.isHidden = false
Рекомендую избавиться от дублирования кода и использовать isCompleted:
plusButtonImage.isHidden = !isCompleted
plusButtonTittle.isHidden = isCompleted

2023-05-02 16:48 UTC, protos17 commented on Tracker/LaunchScreenViewController.swift
> +        setTabBarController()
Для того, чтобы успеть посмотреть LaunchScreen можно написать:
        DispatchQueue.main.asyncAfter(deadline: .now() + 1) { [weak self] in
            self?.setTabBarController()
        }

2023-05-03 08:58 UTC, MaxCode2023 commented on Tracker/TrackersViewController/TrackersViewController.swift
> +    @objc func addButtonTapped() {
plus

2023-05-03 09:01 UTC, MaxCode2023 commented on Tracker/TrackersViewController/TrackerCell/TrackerCell.swift
> +            plusButtonImage.isHidden = false
plus

2023-05-03 09:02 UTC, MaxCode2023 commented on Tracker/LaunchScreenViewController.swift
> +        setTabBarController()
plus

2023-05-03 12:11 UTC, protos17 approved these changes

2023-06-01 18:25 UTC, merged